"""Add custom theme settings to User model

Revision ID: b28025b7fa69
Revises: 1289dbd2ed4a
Create Date: 2025-05-26 20:00:26.648769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b28025b7fa69'
down_revision = '1289dbd2ed4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('custom_font_size', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('custom_bg_primary', sa.String(length=7), nullable=True))
        batch_op.add_column(sa.Column('custom_bg_secondary', sa.String(length=7), nullable=True))
        batch_op.add_column(sa.Column('custom_text_primary', sa.String(length=7), nullable=True))
        batch_op.add_column(sa.Column('custom_text_secondary', sa.String(length=7), nullable=True))
        batch_op.add_column(sa.Column('custom_accent_color', sa.String(length=7), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('custom_accent_color')
        batch_op.drop_column('custom_text_secondary')
        batch_op.drop_column('custom_text_primary')
        batch_op.drop_column('custom_bg_secondary')
        batch_op.drop_column('custom_bg_primary')
        batch_op.drop_column('custom_font_size')

    # ### end Alembic commands ###
